# Generated by Django 5.2.13 on 2026-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getajob', '0003_alter_client_image_alter_job_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/client/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/jobs/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/jobseekers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/vendors/'),
        ),
    ]
