# Generated by Django 5.2.14 on 2026-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getajob', '0004_alter_client_image_alter_job_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
